import React from 'react';
import '../styles/index.css';

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export const metadata = {
  title: {
    default: 'Modern Furniture Store',
    template: 'Modern Furniture Store | %s',
  },
  description: 'Discover premium furniture collections with free delivery, 24/7 support, and professional styling services. Shop dining, living, and bedroom furniture online.',
  keywords: 'furniture store, home decor, dining furniture, living room, bedroom furniture, free delivery, furniture online',
  
  openGraph: {
    type: 'website',
    title: {
      default: 'Modern Furniture Store',
      template: 'Modern Furniture Store | %s',
    },
    description: 'Transform your home with our curated furniture collections. Premium quality, free delivery, and expert styling services for every room.',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}<script type="module" src="https://static.rocket.new/rocket-web.js?_cfg=https%3A%2F%2Fgitanshus1028back.builtwithrocket.new&_be=https%3A%2F%2Fapplication.rocket.new&_v=0.1.8"></script>
</body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
